spring.datasource:
  url: jdbc:h2:mem:envers_example
  username: sa
  password:

spring.h2.console:
  enabled: true
  path: /h2-console

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa:
  hibernate.ddl-auto: create-drop
  properties.hibernate.jdbc.lob.non_contextual_creation: true
