agent-0: &agent-0
  device:
    type: custom
    version: android
  os:
    type: ~
    version: android

agent-1: &agent-1
  device:
    type: desktop
    version: windows

example.like.userAgent:
  local: false
  defaultSutWaitInSeconds: 5
  agents:
    - device:
        type: ${agent-0.device.type}
        version: ${agent-0.device.version}
      os:
        type: ${agent-0.os.type}
        version: ${agent-0.os.version}
    - device:
        type: ${agent-1.device.type}
        version:  ${agent-1.device.version}

